<a href="https://colab.research.google.com/github/chaithanyai311/Artificial-Intelligence-mini-project/blob/main/MachinelearningModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Build a machine learning model ( classification ) - Fruits with colors.txt

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv('fruit_data_with_colors.txt',sep="\t")
df

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

In [ ]:
X = df[['height', 'width', 'mass', 'color_score']]
y = df['fruit_label']
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

KNeighborsClassifier

In [ ]:
#KNeighborsClassifier
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5)
knn.fit(X_train, y_train)

#accuracy
knn.score(X_test, y_test)*100

53.333333333333336

In [ ]:
lookup_fruit_name = dict(zip(df.fruit_label.unique(), df.fruit_name.unique()))
lookup_fruit_name

{1: 'apple', 2: 'mandarin', 3: 'orange', 4: 'lemon'}

In [ ]:
#evaluation
fruit_prediction = knn.predict([[84, 6.0, 4.6,0.79]])
lookup_fruit_name[fruit_prediction[0]]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  "X does not have valid feature names, but"


'mandarin'

Linear regression

In [ ]:
#Linear regression
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(X_train,y_train)

#Accuracy
rscore=regressor.score(X_train,y_train)*100
print(rscore)

76.36348017783092


In [ ]:
#Evaluation
fruit_prediction1 = regressor.predict([[84, 6.0, 4.6,0.79]])
print(fruit_prediction1)

[27.65867452]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


Logistic Regression

In [ ]:
#Logistic regression
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([3, 4, 4, 1, 3, 1, 1, 3, 1, 1, 2, 1, 1, 1, 3])

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_pred,y_test)

array([[3, 0, 5, 0],
       [0, 1, 0, 0],
       [1, 0, 2, 1],
       [0, 0, 1, 1]])

In [ ]:
#Accuracy
accuracy_score(y_pred,y_test)*100

46.666666666666664

Decision Tree classifier

In [ ]:
#Decision tree Classifier
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier(max_depth=2)
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2)

In [ ]:
y_pred = model.predict(X_test)

#Accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)*100

46.666666666666664

In [ ]:
#evaluation
op = model.predict([[84, 6.0, 4.6,0.79]])
lookup_fruit_name[op[0]]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  "X does not have valid feature names, but"


'lemon'

Random Forest Classifier

In [ ]:
#Random forest classifier
from sklearn.preprocessing import MinMaxScaler
s = MinMaxScaler()
X_train = s.fit_transform(X_train)
X_test = s.transform(X_test)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train,y_train) 

RandomForestClassifier()

In [ ]:
y_pred = model.predict(X_test)
y_pred

array([3, 3, 4, 4, 1, 1, 3, 4, 3, 1, 2, 1, 3, 3, 1])

In [ ]:
#Accuracy
accuracy_score(y_pred,y_test)*100

86.66666666666667

Accuracy of multiple ML models

In [ ]:
data={'Accuracy':[53.333333333333336,76.36348017783092,46.666666666666664,46.666666666666664,86.66666666666667]}
datatable = pd.DataFrame(data,index=['KNeighborsClassifier','Linear regression','Logistic regression',
                                     'Decision tree Classifier','Random forest classifier'])
datatable

Accuracy
KNeighborsClassifier      53.333333
Linear regression         76.363480
Logistic regression       46.666667
Decision tree Classifier  46.666667
Random forest classifier  86.666667

Comparing the accuracy of all the model we find that Random forest classifier has higher accuracy than any other ML model